# Generated by Django 5.2 on 2025-04-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalleagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Detalle de agente y aseguradora',
                'verbose_name_plural': 'Detalles de agente y aseguradora',
                'db_table': 'detalleAgAs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleastp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Detalle de aseguradora y tipo de póliza',
                'verbose_name_plural': 'Detalles de aseguradora y tipo de póliza',
                'db_table': 'detalleAsTP',
                'managed': False,
            },
        ),
    ]
