# Generated by Django 5.2 on 2025-04-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('appaterno', models.CharField(db_column='apPaterno', max_length=50, verbose_name='Apellido paterno')),
                ('apmaterno', models.CharField(db_column='apMaterno', max_length=50, verbose_name='Apeliido materno')),
                ('fechanacimineto', models.DateTimeField(db_column='fechaNacimineto', verbose_name='Fecha de nacimineto')),
                ('rfc', models.CharField(db_column='RFC', max_length=13, verbose_name='RFC')),
                ('curp', models.CharField(db_column='CURP', max_length=18, verbose_name='CURP')),
                ('celular', models.CharField(max_length=10, verbose_name='Celular')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('codigopostal', models.CharField(db_column='codigoPostal', max_length=5, verbose_name='Código postal')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('colonia', models.CharField(max_length=50, verbose_name='Colonia')),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('numcasa', models.CharField(db_column='numCasa', max_length=50, verbose_name='Número de casa')),
                ('creado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creado')),
                ('modificado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['-creado'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Generocliente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50, verbose_name='Genero')),
                ('creado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creado')),
                ('modificado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificado')),
            ],
            options={
                'verbose_name': 'Genero de cliente',
                'verbose_name_plural': 'Generos de cliente',
                'db_table': 'generoCliente',
                'ordering': ['-creado'],
                'managed': False,
            },
        ),
    ]
