# Generated by Django 5.2 on 2025-04-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formapago',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=50, verbose_name='Forma de pago')),
                ('creado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creado')),
                ('modificado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificado')),
            ],
            options={
                'verbose_name': 'Forma de pago',
                'verbose_name_plural': 'Formas de pago',
                'db_table': 'formaPago',
                'ordering': ['-creado'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metodopago',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=50, verbose_name='Método de pago')),
                ('creado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creado')),
                ('modificado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificado')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'db_table': 'metodoPago',
                'ordering': ['-creado'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID')),
                ('prima', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prima')),
                ('fechainicio', models.DateTimeField(blank=True, db_column='fechaInicio', null=True, verbose_name='Fehca de inicio')),
                ('fechafin', models.DateTimeField(db_column='fechaFin', verbose_name='Fecha de fin')),
                ('modificado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificado')),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
                'db_table': 'poliza',
                'ordering': ['-fechainicio'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipopoliza',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='tipoPolizas', verbose_name='Imagen')),
                ('creado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creado')),
                ('modificado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificado')),
            ],
            options={
                'verbose_name': 'Tipo de póliza',
                'verbose_name_plural': 'Tipos de póliza',
                'db_table': 'tipoPoliza',
                'ordering': ['-creado'],
                'managed': False,
            },
        ),
    ]
